import json
import subprocess
import os

data = {
    'professions': {
        'ts_file': r'c:\Users\sam\Documents\Projects\wordmask\packages\core\src\packs\data\packs\professions.ts',
        'json_file': r'c:\Users\sam\Documents\Projects\wordmask\packages\core\src\packs\data\professions.json',
        'export_name': 'PROFESSIONS_PACK',
        'category': 'Professions',
        'words': [
            ('Surgeon', 'surgeon', ['operating', 'scalpel', 'doctor']),
            ('Astronaut', 'astronaut', ['space', 'nasa', 'suit']),
            ('Firefighter', 'firefighter', ['hose', 'flames', 'rescue']),
            ('Pilot', 'pilot', ['cockpit', 'flying', 'captain']),
            ('Detective', 'detective', ['clues', 'investigating', 'badge']),
            ('Chef', 'chef_p', ['kitchen', 'cooking', 'toque']),
            ('Lawyer', 'lawyer', ['court', 'defense', 'objection']),
            ('Archaeologist', 'archaeologist', ['digging', 'ancient', 'artifacts']),
            ('Veterinarian', 'veterinarian', ['animal', 'doctor', 'clinic']),
            ('Journalist', 'journalist', ['news', 'reporting', 'press']),
            ('Pharmacist', 'pharmacist', ['medication', 'prescriptions', 'drugstore']),
            ('Architect', 'architect', ['buildings', 'blueprints', 'design']),
            ('Electrician', 'electrician', ['wiring', 'circuits', 'voltage']),
            ('Plumber', 'plumber_p', ['pipes', 'leaks', 'wrench']),
            ('Carpenter', 'carpenter', ['wood', 'hammer', 'building']),
            ('Dentist', 'dentist', ['teeth', 'drill', 'cleaning']),
            ('Professor', 'professor_p', ['university', 'lectures', 'tenure']),
            ('Marine Biologist', 'marine_biologist', ['ocean', 'studying', 'creatures']),
            ('Paramedic', 'paramedic', ['ambulance', 'emergency', 'first']),
            ('Diplomat', 'diplomat', ['embassy', 'negotiation', 'international']),
            ('Park Ranger', 'ranger', ['nature', 'wildlife', 'conservation']),
            ('Stunt Double', 'stuntman', ['dangerous', 'movie', 'substitute']),
            ('Sommelier', 'sommelier', ['wine', 'tasting', 'expert']),
            ('Locksmith', 'locksmith', ['keys', 'opening', 'security']),
            ('Translator', 'translator', ['languages', 'converting', 'bilingual']),
            ('Meteorologist', 'meteorologist', ['weather', 'forecast', 'storms']),
            ('Coroner', 'coroner', ['death', 'autopsy', 'cause']),
            ('Tailor', 'tailor', ['clothing', 'sewing', 'alterations']),
            ('Barista', 'barista', ['coffee', 'espresso', 'cafe']),
            ('Librarian', 'librarian', ['books', 'quiet', 'catalog']),
            ('Optometrist', 'optometrist', ['eyes', 'glasses', 'vision']),
            ('Psychiatrist', 'psychiatrist', ['mental', 'therapy', 'health']),
            ('Accountant', 'accountant', ['taxes', 'numbers', 'finance']),
            ('Florist', 'florist', ['flowers', 'arrangements', 'blooms']),
            ('Butcher', 'butcher', ['meat', 'cutting', 'cleaver']),
            ('Mechanic', 'mechanic', ['cars', 'repair', 'garage']),
            ('Lifeguard', 'lifeguard', ['pool', 'rescue', 'whistle']),
            ('Judge', 'judge', ['court', 'gavel', 'verdict']),
            ('Magician', 'magician', ['tricks', 'illusion', 'wand']),
            ('Clown', 'clown', ['circus', 'funny', 'nose']),
            ('Bartender', 'bartender', ['drinks', 'mixing', 'pub']),
            ('Janitor', 'janitor', ['cleaning', 'mop', 'custodian']),
            ('Roofer', 'roofer', ['shingles', 'house', 'top']),
            ('Mason', 'mason', ['bricks', 'mortar', 'laying']),
            ('Welder', 'welder', ['metal', 'torch', 'sparks']),
            ('Geologist', 'geologist', ['rocks', 'earth', 'minerals']),
            ('Botanist', 'botanist', ['plants', 'studying', 'flora']),
            ('Zoologist', 'zoologist', ['animals', 'research', 'fauna']),
            ('Astronomer', 'astronomer', ['stars', 'telescope', 'cosmos']),
            ('Physicist', 'physicist', ['matter', 'energy', 'laws']),
            ('Chemist', 'chemist', ['reactions', 'beakers', 'lab']),
            ('Biologist', 'biologist', ['life', 'cells', 'organisms']),
            ('Historian', 'historian', ['past', 'events', 'research']),
            ('Economist', 'economist', ['markets', 'wealth', 'analysis']),
            ('Sociologist', 'sociologist', ['society', 'culture', 'groups']),
            ('Anthropologist', 'anthropologist', ['humans', 'cultures', 'origins']),
            ('Philosopher', 'philosopher', ['thinking', 'existence', 'ideas']),
            ('Mathematician', 'mathematician', ['numbers', 'equations', 'logic']),
            ('Statistician', 'statistician', ['data', 'probability', 'analysis']),
            ('Actuary', 'actuary', ['risk', 'insurance', 'math']),
            ('Surveyor', 'surveyor', ['land', 'measuring', 'boundaries']),
            ('Cartographer', 'cartographer', ['maps', 'drawing', 'geography']),
            ('Photographer', 'photographer', ['camera', 'pictures', 'lens']),
            ('Videographer', 'videographer', ['filming', 'movies', 'recording']),
            ('Editor', 'editor', ['text', 'correcting', 'publishing']),
            ('Publisher', 'publisher', ['books', 'printing', 'distribution']),
            ('Author', 'author', ['writing', 'novels', 'creator']),
            ('Poet', 'poet', ['rhymes', 'verses', 'writing']),
            ('Novelist', 'novelist', ['fiction', 'books', 'stories']),
            ('Playwright', 'playwright', ['theater', 'scripts', 'drama']),
            ('Screenwriter', 'screenwriter', ['movies', 'scripts', 'film']),
            ('Director', 'director', ['movies', 'action', 'cut']),
            ('Producer', 'producer', ['funding', 'movies', 'music']),
            ('Actor', 'actor', ['stage', 'movies', 'performing']),
            ('Actress', 'actress', ['female', 'performer', 'film']),
            ('Singer', 'singer', ['vocals', 'music', 'performing']),
            ('Musician', 'musician', ['instruments', 'playing', 'band']),
            ('Composer', 'composer', ['music', 'writing', 'notes']),
            ('Conductor', 'conductor', ['orchestra', 'baton', 'leading']),
            ('Choreographer', 'choreographer', ['dance', 'routines', 'steps']),
            ('Dancer', 'dancer', ['movement', 'rhythm', 'stage']),
            ('Painter', 'painter', ['canvas', 'brush', 'colors']),
            ('Sculptor', 'sculptor', ['clay', 'stone', 'carving']),
            ('Illustrator', 'illustrator', ['drawing', 'pictures', 'art']),
            ('Designer', 'designer', ['creating', 'style', 'layout']),
            ('Model', 'model', ['fashion', 'posing', 'runway']),
            ('Stylist', 'stylist', ['clothes', 'hair', 'look']),
            ('Makeup Artist', 'makeup_artist', ['cosmetics', 'faces', 'beauty']),
            ('Hairdresser', 'hairdresser', ['salon', 'cutting', 'styling']),
            ('Barber', 'barber', ['men', 'hair', 'shaving']),
            ('Masseuse', 'masseuse', ['massage', 'spa', 'relax']),
            ('Therapist', 'therapist', ['counseling', 'mental', 'help']),
            ('Counselor', 'counselor', ['advice', 'guidance', 'school']),
            ('Coach', 'coach', ['sports', 'training', 'team']),
            ('Referee', 'referee', ['whistle', 'rules', 'sports']),
            ('Umpire', 'umpire', ['baseball', 'calls', 'strike']),
            ('Trainer', 'trainer', ['fitness', 'gym', 'workout']),
            ('Dietitian', 'dietitian', ['food', 'nutrition', 'health']),
            ('Nutritionist', 'nutritionist', ['diet', 'eating', 'wellness']),
            ('Pediatrician', 'pediatrician', ['children', 'doctor', 'kids']),
            ('Nurse', 'nurse', ['hospital', 'care', 'patients']),
            ('Midwife', 'midwife', ['babies', 'birth', 'delivery']),
            ('Doula', 'doula', ['support', 'birth', 'pregnancy']),
            ('Gynecologist', 'gynecologist', ['women', 'health', 'doctor']),
            ('Obstetrician', 'obstetrician', ['pregnancy', 'doctor', 'birth']),
            ('Cardiologist', 'cardiologist', ['heart', 'doctor', 'health']),
            ('Dermatologist', 'dermatologist', ['skin', 'doctor', 'acne']),
            ('Neurologist', 'neurologist', ['brain', 'nerves', 'doctor']),
            ('Oncologist', 'oncologist', ['cancer', 'doctor', 'tumors']),
            ('Radiologist', 'radiologist', ['x-rays', 'scans', 'doctor']),
            ('Pathologist', 'pathologist', ['disease', 'lab', 'doctor']),
            ('Anesthesiologist', 'anesthesiologist', ['sleep', 'surgery', 'gas']),
            ('Optician', 'optician', ['glasses', 'lenses', 'fitting']),
            ('Audiologist', 'audiologist', ['hearing', 'ears', 'doctor']),
            ('Chiropractor', 'chiropractor', ['back', 'spine', 'cracking']),
            ('Physiotherapist', 'physiotherapist', ['movement', 'healing', 'exercises']),
            ('Podiatrist', 'podiatrist', ['feet', 'doctor', 'toes']),
            ('Phlebotomist', 'phlebotomist', ['blood', 'drawing', 'needles']),
            ('Blacksmith', 'blacksmith', ['forge', 'anvil', 'iron']),
            ('Seamstress', 'seamstress', ['sewing', 'clothes', 'needle']),
            ('Plumber2', 'plumber2', ['drains', 'fixing', 'spanner'])
        ]
    },
    'randomObjects': {
        'ts_file': r'c:\Users\sam\Documents\Projects\wordmask\packages\core\src\packs\data\packs\randomObjects.ts',
        'json_file': r'c:\Users\sam\Documents\Projects\wordmask\packages\core\src\packs\data\random-objects.json',
        'export_name': 'RANDOM_OBJECTS_PACK',
        'category': 'Random Objects',
        'words': [
            ('Stapler', 'stapler', ['office', 'binding', 'metal']),
            ('Teapot', 'teapot', ['brewing', 'spout', 'handle']),
            ('Spatula', 'spatula', ['flipping', 'kitchen', 'cooking']),
            ('Umbrella', 'umbrella', ['rain', 'shield', 'canopy']),
            ('Toaster', 'toaster', ['bread', 'crispy', 'kitchen']),
            ('Toothbrush', 'toothbrush', ['dental', 'bristles', 'cleaning']),
            ('Hairbrush', 'hairbrush', ['grooming', 'tangles', 'bristles']),
            ('Comb', 'comb', ['hair', 'teeth', 'styling']),
            ('Mirror', 'mirror', ['reflection', 'glass', 'looking']),
            ('Towel', 'towel', ['drying', 'bath', 'fabric']),
            ('Soap', 'soap', ['washing', 'lather', 'clean']),
            ('Shampoo', 'shampoo', ['hair', 'washing', 'bottle']),
            ('Conditioner', 'conditioner', ['hair', 'soft', 'bottle']),
            ('Lotion', 'lotion', ['skin', 'moisturize', 'bottle']),
            ('Deodorant', 'deodorant', ['smell', 'underarm', 'stick']),
            ('Perfume', 'perfume', ['scent', 'spray', 'bottle']),
            ('Cologne', 'cologne', ['scent', 'spray', 'men']),
            ('Toothpaste', 'toothpaste', ['mint', 'brushing', 'tube']),
            ('Floss', 'floss', ['teeth', 'string', 'dental']),
            ('Mouthwash', 'mouthwash', ['rinse', 'breath', 'liquid']),
            ('Razor', 'razor', ['shaving', 'blades', 'handle']),
            ('Shaving Cream', 'shaving_cream', ['foam', 'face', 'can']),
            ('Tweezers', 'tweezers', ['plucking', 'metal', 'small']),
            ('Nail Clippers', 'nail_clippers', ['trimming', 'fingers', 'metal']),
            ('Cotton Swabs', 'cotton_swabs', ['ears', 'cleaning', 'sticks']),
            ('Cotton Balls', 'cotton_balls', ['soft', 'white', 'fluffy']),
            ('Bandage', 'bandage', ['cuts', 'healing', 'sticky']),
            ('Thermometer', 'thermometer', ['temperature', 'fever', 'measuring']),
            ('Pill Bottle', 'pill_bottle', ['medicine', 'plastic', 'cap']),
            ('Syringe', 'syringe', ['needle', 'inject', 'medical']),
            ('Stethoscope', 'stethoscope', ['heartbeat', 'listening', 'doctor']),
            ('Scalpel', 'scalpel', ['cutting', 'surgery', 'blade']),
            ('Crutches', 'crutches', ['walking', 'injury', 'support']),
            ('Wheelchair', 'wheelchair', ['rolling', 'sitting', 'mobility']),
            ('Walker', 'walker', ['support', 'elderly', 'moving']),
            ('Cane', 'cane', ['walking', 'stick', 'support']),
            ('Glasses', 'glasses', ['vision', 'lenses', 'frames']),
            ('Contacts', 'contacts', ['eyes', 'lenses', 'vision']),
            ('Sunglasses', 'sunglasses', ['shade', 'eyes', 'dark']),
            ('Hat', 'hat', ['head', 'wearing', 'cap']),
            ('Scarf', 'scarf', ['neck', 'warm', 'winter']),
            ('Gloves', 'gloves', ['hands', 'warm', 'fingers']),
            ('Mittens', 'mittens', ['hands', 'winter', 'warm']),
            ('Socks', 'socks', ['feet', 'wearing', 'warm']),
            ('Shoes', 'shoes', ['feet', 'walking', 'soles']),
            ('Boots', 'boots', ['feet', 'winter', 'heavy']),
            ('Sandals', 'sandals', ['feet', 'summer', 'open']),
            ('Slippers', 'slippers', ['feet', 'indoor', 'cozy']),
            ('Belt', 'belt', ['waist', 'leather', 'buckle']),
            ('Tie', 'tie', ['neck', 'suit', 'knot']),
            ('Watch', 'watch', ['wrist', 'time', 'clock']),
            ('Bracelet', 'bracelet', ['wrist', 'jewelry', 'band']),
            ('Necklace', 'necklace', ['neck', 'jewelry', 'chain']),
            ('Ring', 'ring', ['finger', 'jewelry', 'band']),
            ('Earrings', 'earrings', ['ears', 'jewelry', 'lobes']),
            ('Purse', 'purse', ['bag', 'carrying', 'women']),
            ('Wallet', 'wallet', ['money', 'cards', 'pocket']),
            ('Backpack', 'backpack', ['school', 'carrying', 'straps']),
            ('Briefcase', 'briefcase', ['office', 'carrying', 'handle']),
            ('Suitcase', 'suitcase', ['travel', 'luggage', 'wheels']),
            ('Duffel Bag', 'duffel_bag', ['gym', 'carrying', 'canvas']),
            ('Tote Bag', 'tote_bag', ['shopping', 'carrying', 'canvas']),
            ('Paper Bag', 'paper_bag', ['groceries', 'brown', 'sack']),
            ('Plastic Bag', 'plastic_bag', ['shopping', 'thin', 'sack']),
            ('Garbage Bag', 'garbage_bag', ['trash', 'black', 'plastic']),
            ('Trash Can', 'trash_can', ['garbage', 'bin', 'waste']),
            ('Recycling Bin', 'recycling_bin', ['blue', 'plastic', 'cans']),
            ('Broom', 'broom', ['sweeping', 'floor', 'bristles']),
            ('Dustpan', 'dustpan', ['sweeping', 'dirt', 'plastic']),
            ('Mop', 'mop', ['cleaning', 'floor', 'wet']),
            ('Bucket', 'bucket', ['water', 'pail', 'handle']),
            ('Sponge', 'sponge', ['washing', 'dishes', 'absorbent']),
            ('Dish Soap', 'dish_soap', ['washing', 'plates', 'liquid']),
            ('Laundry Detergent', 'laundry_detergent', ['washing', 'clothes', 'soap']),
            ('Fabric Softener', 'fabric_softener', ['clothes', 'laundry', 'liquid']),
            ('Bleach', 'bleach', ['cleaning', 'white', 'liquid']),
            ('Iron', 'iron', ['clothes', 'wrinkles', 'heat']),
            ('Ironing Board', 'ironing_board', ['clothes', 'pressing', 'stand']),
            ('Vacuum', 'vacuum', ['cleaning', 'carpet', 'suction']),
            ('Feather Duster', 'feather_duster', ['cleaning', 'dust', 'fluffy']),
            ('Window Cleaner', 'window_cleaner', ['glass', 'spray', 'blue']),
            ('Paper Towels', 'paper_towels', ['wiping', 'roll', 'kitchen']),
            ('Toilet Paper', 'toilet_paper', ['bathroom', 'roll', 'soft']),
            ('Tissues', 'tissues', ['nose', 'blowing', 'box']),
            ('Napkins', 'napkins', ['mouth', 'wiping', 'table']),
            ('Plates', 'plates', ['eating', 'round', 'dishes']),
            ('Bowls', 'bowls', ['soup', 'eating', 'dishes']),
            ('Cups', 'cups', ['drinking', 'glasses', 'liquid']),
            ('Mugs', 'mugs', ['coffee', 'drinking', 'handle']),
            ('Forks', 'forks', ['eating', 'prongs', 'silverware']),
            ('Knives', 'knives', ['cutting', 'eating', 'silverware']),
            ('Spoons', 'spoons', ['eating', 'soup', 'silverware']),
            ('Chopsticks', 'chopsticks', ['eating', 'asian', 'sticks']),
            ('Pots', 'pots', ['cooking', 'stove', 'metal']),
            ('Pans', 'pans', ['frying', 'stove', 'metal']),
            ('Baking Sheet', 'baking_sheet', ['oven', 'cookies', 'metal']),
            ('Cutting Board', 'cutting_board', ['chopping', 'wood', 'kitchen']),
            ('Rolling Pin', 'rolling_pin', ['dough', 'baking', 'wood']),
            ('Measuring Cups', 'measuring_cups', ['baking', 'amounts', 'kitchen']),
            ('Measuring Spoons', 'measuring_spoons', ['baking', 'small', 'amounts']),
            ('Whisk', 'whisk', ['mixing', 'eggs', 'wire']),
            ('Can Opener', 'can_opener', ['tins', 'opening', 'metal']),
            ('Bottle Opener', 'bottle_opener', ['caps', 'opening', 'metal']),
            ('Corkscrew', 'corkscrew', ['wine', 'opening', 'metal']),
            ('Peeler', 'peeler', ['potatoes', 'skin', 'metal']),
            ('Grater', 'grater', ['cheese', 'shredding', 'metal']),
            ('Colander', 'colander', ['straining', 'pasta', 'holes']),
            ('Strainer', 'strainer', ['filtering', 'liquid', 'mesh']),
            ('Tongs', 'tongs', ['grabbing', 'cooking', 'metal']),
            ('Ladle', 'ladle', ['soup', 'scooping', 'spoon']),
            ('Oven Mitts', 'oven_mitts', ['baking', 'heat', 'hands']),
            ('Apron', 'apron', ['cooking', 'clothes', 'protection']),
            ('Dish Towel', 'dish_towel', ['drying', 'kitchen', 'cloth']),
            ('Placemat', 'placemat', ['table', 'setting', 'mat']),
            ('Tablecloth', 'tablecloth', ['table', 'covering', 'fabric']),
            ('Centerpiece', 'centerpiece', ['table', 'decoration', 'middle']),
            ('Candle', 'candle', ['wax', 'flame', 'wick']),
            ('Matches', 'matches', ['fire', 'striking', 'sticks']),
            ('Lighter', 'lighter', ['fire', 'flame', 'plastic']),
            ('Flashlight', 'flashlight', ['light', 'dark', 'beam']),
            ('Batteries', 'batteries', ['power', 'energy', 'cells'])
        ]
    },
    'science': {
        'ts_file': r'c:\Users\sam\Documents\Projects\wordmask\packages\core\src\packs\data\packs\science.ts',
        'json_file': r'c:\Users\sam\Documents\Projects\wordmask\packages\core\src\packs\data\science.json',
        'export_name': 'SCIENCE_PACK',
        'category': 'Science',
        'words': [
            ('Microscope', 'microscope', ['lens', 'zooming', 'cells']),
            ('Telescope', 'telescope', ['stars', 'astronomy', 'space']),
            ('Beaker', 'beaker', ['glass', 'liquids', 'lab']),
            ('Flask', 'flask', ['chemistry', 'glassware', 'neck']),
            ('Test Tube', 'test_tube', ['glass', 'small', 'reactions']),
            ('Bunsen Burner', 'bunsen_burner', ['flame', 'heating', 'gas']),
            ('Pipette', 'pipette', ['drops', 'liquid', 'transfer']),
            ('Petri Dish', 'petri_dish', ['bacteria', 'culture', 'flat']),
            ('Thermometer', 'thermometer', ['temperature', 'measuring', 'heat']),
            ('Barometer', 'barometer', ['pressure', 'weather', 'measuring']),
            ('Anemometer', 'anemometer', ['wind', 'speed', 'weather']),
            ('Hygrometer', 'hygrometer', ['humidity', 'moisture', 'weather']),
            ('Seismograph', 'seismograph', ['earthquakes', 'tremors', 'measuring']),
            ('Spectrometer', 'spectrometer', ['light', 'wavelengths', 'measuring']),
            ('Centrifuge', 'centrifuge', ['spinning', 'separating', 'liquids']),
            ('Incubator', 'incubator', ['warmth', 'growing', 'cultures']),
            ('Autoclave', 'autoclave', ['sterilizing', 'heat', 'pressure']),
            ('Fume Hood', 'fume_hood', ['ventilation', 'gases', 'safety']),
            ('Safety Goggles', 'safety_goggles', ['eyes', 'protection', 'glasses']),
            ('Lab Coat', 'lab_coat', ['clothing', 'white', 'protection']),
            ('Gloves', 'gloves', ['hands', 'protection', 'latex']),
            ('Scalpel', 'scalpel', ['cutting', 'surgery', 'blade']),
            ('Forceps', 'forceps', ['grabbing', 'tweezers', 'surgical']),
            ('Syringe', 'syringe', ['needle', 'inject', 'medical']),
            ('Stethoscope', 'stethoscope', ['heartbeat', 'listening', 'doctor']),
            ('Sphygmomanometer', 'sphygmomanometer', ['blood', 'pressure', 'cuff']),
            ('Electrocardiogram', 'electrocardiogram', ['heart', 'electrical', 'graph']),
            ('Electroencephalogram', 'electroencephalogram', ['brain', 'waves', 'graph']),
            ('Ultrasound', 'ultrasound', ['sound', 'imaging', 'pregnancy']),
            ('X-ray', 'x_ray', ['bones', 'imaging', 'radiation']),
            ('MRI', 'mri', ['magnetic', 'imaging', 'scanner']),
            ('CT Scan', 'ct_scan', ['computed', 'tomography', 'imaging']),
            ('PET Scan', 'pet_scan', ['positron', 'emission', 'imaging']),
            ('DNA', 'dna', ['genetics', 'helix', 'code']),
            ('RNA', 'rna', ['genetics', 'ribonucleic', 'acid']),
            ('Chromosome', 'chromosome', ['genetics', 'thread', 'nucleus']),
            ('Gene', 'gene', ['heredity', 'traits', 'dna']),
            ('Allele', 'allele', ['variant', 'gene', 'mutation']),
            ('Mutation', 'mutation', ['change', 'dna', 'genetic']),
            ('Evolution', 'evolution', ['change', 'species', 'time']),
            ('Natural Selection', 'natural_selection', ['survival', 'fittest', 'evolution']),
            ('Adaptation', 'adaptation', ['trait', 'survival', 'environment']),
            ('Speciation', 'speciation', ['formation', 'new', 'species']),
            ('Extinction', 'extinction', ['death', 'species', 'gone']),
            ('Fossil', 'fossil', ['remains', 'ancient', 'stone']),
            ('Dinosaur', 'dinosaur', ['extinct', 'reptile', 'ancient']),
            ('Mammoth', 'mammoth', ['extinct', 'elephant', 'ice']),
            ('Neanderthal', 'neanderthal', ['extinct', 'human', 'caveman']),
            ('Homo Sapiens', 'homo_sapiens', ['modern', 'human', 'species']),
            ('Cell', 'cell', ['basic', 'unit', 'life']),
            ('Nucleus', 'nucleus', ['center', 'cell', 'control']),
            ('Mitochondria', 'mitochondria', ['powerhouse', 'cell', 'energy']),
            ('Chloroplast', 'chloroplast', ['plants', 'photosynthesis', 'green']),
            ('Ribosome', 'ribosome', ['protein', 'synthesis', 'cell']),
            ('Endoplasmic Reticulum', 'endoplasmic_reticulum', ['network', 'cell', 'transport']),
            ('Golgi Apparatus', 'golgi_apparatus', ['packaging', 'cell', 'proteins']),
            ('Lysosome', 'lysosome', ['digestion', 'cell', 'waste']),
            ('Vacuole', 'vacuole', ['storage', 'cell', 'water']),
            ('Cell Membrane', 'cell_membrane', ['boundary', 'cell', 'lipid']),
            ('Cell Wall', 'cell_wall', ['plants', 'structure', 'rigid']),
            ('Cytoplasm', 'cytoplasm', ['jelly', 'cell', 'fluid']),
            ('Enzyme', 'enzyme', ['catalyst', 'protein', 'reaction']),
            ('Protein', 'protein', ['amino', 'acids', 'building']),
            ('Carbohydrate', 'carbohydrate', ['sugar', 'energy', 'food']),
            ('Lipid', 'lipid', ['fat', 'oil', 'energy']),
            ('Nucleic Acid', 'nucleic_acid', ['dna', 'rna', 'genetic']),
            ('Atom', 'atom', ['basic', 'unit', 'matter']),
            ('Proton', 'proton', ['positive', 'charge', 'nucleus']),
            ('Neutron', 'neutron', ['neutral', 'charge', 'nucleus']),
            ('Electron', 'electron', ['negative', 'charge', 'orbit']),
            ('Ion', 'ion', ['charged', 'atom', 'particle']),
            ('Isotope', 'isotope', ['variant', 'element', 'neutrons']),
            ('Molecule', 'molecule', ['atoms', 'bonded', 'together']),
            ('Compound', 'compound', ['elements', 'bonded', 'together']),
            ('Mixture', 'mixture', ['substances', 'combined', 'physical']),
            ('Solution', 'solution', ['homogeneous', 'mixture', 'dissolved']),
            ('Solvent', 'solvent', ['dissolving', 'substance', 'liquid']),
            ('Solute', 'solute', ['dissolved', 'substance', 'solid']),
            ('Acid', 'acid', ['sour', 'ph', 'low']),
            ('Base', 'base', ['bitter', 'ph', 'high']),
            ('Salt', 'salt', ['ionic', 'compound', 'sodium']),
            ('Reaction', 'reaction', ['chemical', 'change', 'process']),
            ('Catalyst', 'catalyst', ['speeding', 'reaction', 'enzyme']),
            ('Gravity', 'gravity', ['force', 'attraction', 'mass']),
            ('Friction', 'friction', ['resistance', 'motion', 'rubbing']),
            ('Inertia', 'inertia', ['resistance', 'change', 'motion']),
            ('Momentum', 'momentum', ['mass', 'velocity', 'motion']),
            ('Energy', 'energy', ['capacity', 'work', 'power']),
            ('Work', 'work', ['force', 'distance', 'energy']),
            ('Power', 'power', ['rate', 'work', 'energy']),
            ('Heat', 'heat', ['thermal', 'energy', 'temperature']),
            ('Light', 'light', ['electromagnetic', 'radiation', 'visible']),
            ('Sound', 'sound', ['vibration', 'waves', 'hearing']),
            ('Electricity', 'electricity', ['flow', 'electrons', 'current']),
            ('Magnetism', 'magnetism', ['attraction', 'repulsion', 'poles']),
            ('Circuit', 'circuit', ['path', 'electricity', 'flow']),
            ('Voltage', 'voltage', ['potential', 'difference', 'electrical']),
            ('Current', 'current', ['flow', 'charge', 'electrical']),
            ('Resistance', 'resistance', ['opposition', 'flow', 'electrical']),
            ('Conductor', 'conductor', ['allows', 'flow', 'electrical']),
            ('Insulator', 'insulator', ['blocks', 'flow', 'electrical']),
            ('Semiconductor', 'semiconductor', ['partial', 'flow', 'electrical']),
            ('Transistor', 'transistor', ['switch', 'amplifier', 'electronic']),
            ('Diode', 'diode', ['one-way', 'flow', 'electronic']),
            ('Capacitor', 'capacitor', ['storage', 'charge', 'electronic']),
            ('Resistor', 'resistor', ['opposition', 'flow', 'electronic']),
            ('Inductor', 'inductor', ['storage', 'magnetic', 'electronic']),
            ('Transformer', 'transformer', ['changing', 'voltage', 'electrical']),
            ('Motor', 'motor', ['converting', 'electrical', 'mechanical']),
            ('Generator', 'generator', ['converting', 'mechanical', 'electrical']),
            ('Battery', 'battery', ['storage', 'chemical', 'electrical']),
            ('Solar Cell', 'solar_cell', ['converting', 'light', 'electrical']),
            ('Fuel Cell', 'fuel_cell', ['converting', 'chemical', 'electrical']),
            ('Planet', 'planet', ['orbiting', 'star', 'celestial']),
            ('Star', 'star', ['luminous', 'plasma', 'celestial']),
            ('Galaxy', 'galaxy', ['system', 'stars', 'universe']),
            ('Universe', 'universe', ['all', 'space', 'time']),
            ('Black Hole', 'black_hole', ['gravity', 'light', 'escape']),
            ('Supernova', 'supernova', ['explosion', 'star', 'stellar']),
            ('Asteroid', 'asteroid', ['rock', 'space', 'orbit'])
        ]
    },
    'sports': {
        'ts_file': r'c:\Users\sam\Documents\Projects\wordmask\packages\core\src\packs\data\packs\sports.ts',
        'json_file': r'c:\Users\sam\Documents\Projects\wordmask\packages\core\src\packs\data\sports.json',
        'export_name': 'SPORTS_PACK',
        'category': 'Sports',
        'words': [
            ('Soccer', 'soccer', ['football', 'pitch', 'goal']),
            ('Basketball', 'basketball', ['hoop', 'dribble', 'court']),
            ('Baseball', 'baseball', ['diamond', 'bat', 'homerun']),
            ('Football', 'football', ['touchdown', 'gridiron', 'helmet']),
            ('Tennis', 'tennis', ['racket', 'net', 'serve']),
            ('Golf', 'golf', ['clubs', 'links', 'hole']),
            ('Hockey', 'hockey', ['puck', 'ice', 'skates']),
            ('Volleyball', 'volleyball', ['net', 'spike', 'sand']),
            ('Rugby', 'rugby', ['scrum', 'try', 'pitch']),
            ('Cricket', 'cricket', ['wicket', 'bat', 'pitch']),
            ('Table Tennis', 'table_tennis', ['ping', 'pong', 'paddle']),
            ('Badminton', 'badminton', ['shuttlecock', 'net', 'racket']),
            ('Squash', 'squash', ['racket', 'wall', 'court']),
            ('Racquetball', 'racquetball', ['racket', 'wall', 'court']),
            ('Lacrosse', 'lacrosse', ['stick', 'net', 'field']),
            ('Field Hockey', 'field_hockey', ['stick', 'ball', 'grass']),
            ('Water Polo', 'water_polo', ['pool', 'ball', 'goal']),
            ('Swimming', 'swimming', ['pool', 'laps', 'strokes']),
            ('Diving', 'diving', ['board', 'pool', 'flip']),
            ('Surfing', 'surfing', ['waves', 'ocean', 'ride']),
            ('Skateboarding', 'skateboarding', ['deck', 'wheels', 'tricks']),
            ('Snowboarding', 'snowboarding', ['snow', 'mountain', 'ride']),
            ('Skiing', 'skiing', ['snow', 'mountain', 'poles']),
            ('Ice Skating', 'ice_skating', ['blades', 'rink', 'glide']),
            ('Figure Skating', 'figure_skating', ['ice', 'jumps', 'dance']),
            ('Speed Skating', 'speed_skating', ['ice', 'racing', 'track']),
            ('Bobsleigh', 'bobsleigh', ['ice', 'track', 'team']),
            ('Luge', 'luge', ['ice', 'track', 'sled']),
            ('Skeleton', 'skeleton', ['ice', 'track', 'headfirst']),
            ('Curling', 'curling', ['ice', 'stones', 'sweeping']),
            ('Gymnastics', 'gymnastics', ['flips', 'bars', 'beam']),
            ('Trampolining', 'trampolining', ['bouncing', 'flips', 'air']),
            ('Cheerleading', 'cheerleading', ['stunts', 'pom', 'poms']),
            ('Dance', 'dance', ['movement', 'music', 'rhythm']),
            ('Martial Arts', 'martial_arts', ['fighting', 'discipline', 'dojo']),
            ('Karate', 'karate', ['striking', 'kicking', 'belt']),
            ('Judo', 'judo', ['throwing', 'grappling', 'belt']),
            ('Taekwondo', 'taekwondo', ['kicking', 'striking', 'belt']),
            ('Kung Fu', 'kung_fu', ['chinese', 'martial', 'arts']),
            ('Tai Chi', 'tai_chi', ['slow', 'movement', 'balance']),
            ('Boxing', 'boxing', ['gloves', 'ring', 'punching']),
            ('Kickboxing', 'kickboxing', ['punching', 'kicking', 'ring']),
            ('Muay Thai', 'muay_thai', ['striking', 'clinching', 'ring']),
            ('Wrestling', 'wrestling', ['grappling', 'pin', 'mat']),
            ('Sumo', 'sumo', ['japanese', 'wrestling', 'ring']),
            ('Fencing', 'fencing', ['sword', 'foil', 'mask']),
            ('Archery', 'archery', ['bow', 'arrow', 'target']),
            ('Shooting', 'shooting', ['gun', 'target', 'aim']),
            ('Equestrian', 'equestrian', ['horses', 'riding', 'jumping']),
            ('Polo', 'polo', ['horses', 'mallet', 'ball']),
            ('Horse Racing', 'horse_racing', ['jockey', 'track', 'derby']),
            ('Greyhound Racing', 'greyhound_racing', ['dogs', 'track', 'lure']),
            ('Motor Racing', 'motor_racing', ['cars', 'track', 'speed']),
            ('Formula One', 'formula_one', ['cars', 'racing', 'track']),
            ('NASCAR', 'nascar', ['stock', 'cars', 'oval']),
            ('IndyCar', 'indycar', ['open', 'wheel', 'racing']),
            ('Rallying', 'rallying', ['cars', 'dirt', 'racing']),
            ('Motocross', 'motocross', ['motorcycles', 'dirt', 'racing']),
            ('Supercross', 'supercross', ['motorcycles', 'stadium', 'racing']),
            ('MotoGP', 'motogp', ['motorcycles', 'road', 'racing']),
            ('Cycling', 'cycling', ['bicycle', 'riding', 'pedals']),
            ('Road Cycling', 'road_cycling', ['bicycle', 'paved', 'racing']),
            ('Track Cycling', 'track_cycling', ['bicycle', 'velodrome', 'racing']),
            ('Mountain Biking', 'mountain_biking', ['bicycle', 'trails', 'dirt']),
            ('BMX', 'bmx', ['bicycle', 'dirt', 'tricks']),
            ('Triathlon', 'triathlon', ['swim', 'bike', 'run']),
            ('Decathlon', 'decathlon', ['ten', 'events', 'athletics']),
            ('Heptathlon', 'heptathlon', ['seven', 'events', 'athletics']),
            ('Pentathlon', 'pentathlon', ['five', 'events', 'athletics']),
            ('Track and Field', 'track_and_field', ['running', 'jumping', 'throwing']),
            ('Marathon', 'marathon', ['running', 'distance', 'race']),
            ('Sprinting', 'sprinting', ['running', 'fast', 'short']),
            ('Hurdles', 'hurdles', ['running', 'jumping', 'obstacles']),
            ('Relay', 'relay', ['team', 'baton', 'race']),
            ('High Jump', 'high_jump', ['bar', 'leaping', 'athletics']),
            ('Pole Vault', 'pole_vault', ['stick', 'leaping', 'athletics']),
            ('Long Jump', 'long_jump', ['sand', 'leaping', 'athletics']),
            ('Triple Jump', 'triple_jump', ['hop', 'step', 'leap']),
            ('Shot Put', 'shot_put', ['heavy', 'ball', 'throwing']),
            ('Discus', 'discus', ['heavy', 'disc', 'throwing']),
            ('Hammer Throw', 'hammer_throw', ['heavy', 'ball', 'wire']),
            ('Javelin', 'javelin', ['spear', 'throwing', 'athletics']),
            ('Rowing', 'rowing', ['boat', 'oars', 'water']),
            ('Canoeing', 'canoeing', ['boat', 'paddle', 'water']),
            ('Kayaking', 'kayaking', ['boat', 'double', 'paddle']),
            ('Sailing', 'sailing', ['boat', 'wind', 'water']),
            ('Windsurfing', 'windsurfing', ['board', 'sail', 'water']),
            ('Kiteboarding', 'kiteboarding', ['board', 'kite', 'water']),
            ('Wakeboarding', 'wakeboarding', ['board', 'boat', 'water']),
            ('Water Skiing', 'water_skiing', ['skis', 'boat', 'water']),
            ('Fishing', 'fishing', ['rod', 'reel', 'water']),
            ('Hunting', 'hunting', ['gun', 'animals', 'woods']),
            ('Hiking', 'hiking', ['walking', 'trails', 'nature']),
            ('Rock Climbing', 'rock_climbing', ['walls', 'ropes', 'harness']),
            ('Bouldering', 'bouldering', ['walls', 'no', 'ropes']),
            ('Mountaineering', 'mountaineering', ['climbing', 'peaks', 'ice']),
            ('Orienteering', 'orienteering', ['map', 'compass', 'navigating']),
            ('Geocaching', 'geocaching', ['gps', 'treasure', 'hunting']),
            ('Paintball', 'paintball', ['guns', 'colors', 'shooting']),
            ('Airsoft', 'airsoft', ['guns', 'pellets', 'shooting']),
            ('Laser Tag', 'laser_tag', ['guns', 'beams', 'shooting']),
            ('Bowling', 'bowling', ['pins', 'alley', 'heavy']),
            ('Billiards', 'billiards', ['pool', 'cues', 'balls']),
            ('Snooker', 'snooker', ['pool', 'cues', 'table']),
            ('Darts', 'darts', ['board', 'throwing', 'pub']),
            ('Archery Tag', 'archery_tag', ['bows', 'arrows', 'shooting']),
            ('Dodgeball', 'dodgeball', ['throwing', 'ducking', 'court']),
            ('Kickball', 'kickball', ['foot', 'bases', 'diamond']),
            ('Tetherball', 'tetherball', ['pole', 'rope', 'hitting']),
            ('Four Square', 'four_square', ['court', 'bouncing', 'playground']),
            ('Handball', 'handball', ['wall', 'hitting', 'court']),
            ('Frisbee', 'frisbee', ['disc', 'throwing', 'catching']),
            ('Ultimate Frisbee', 'ultimate_frisbee', ['disc', 'team', 'field']),
            ('Disc Golf', 'disc_golf', ['frisbee', 'baskets', 'course']),
            ('Bocce', 'bocce', ['balls', 'grass', 'rolling']),
            ('Croquet', 'croquet', ['mallets', 'wickets', 'grass']),
            ('Horseshoes', 'horseshoes', ['throwing', 'stakes', 'metal']),
            ('Cornhole', 'cornhole', ['bags', 'boards', 'tossing']),
            ('Shuffleboard', 'shuffleboard', ['pucks', 'sliding', 'court']),
            ('Pickleball', 'pickleball', ['paddle', 'net', 'court'])
        ]
    },
    'technology': {
        'ts_file': r'c:\Users\sam\Documents\Projects\wordmask\packages\core\src\packs\data\packs\technology.ts',
        'json_file': r'c:\Users\sam\Documents\Projects\wordmask\packages\core\src\packs\data\technology.json',
        'export_name': 'TECHNOLOGY_PACK',
        'category': 'Technology',
        'words': [
            ('Computer', 'computer', ['desktop', 'processing', 'machine']),
            ('Laptop', 'laptop', ['portable', 'keyboard', 'screen']),
            ('Smartphone', 'smartphone', ['mobile', 'touch', 'device']),
            ('Tablet', 'tablet', ['touchscreen', 'portable', 'device']),
            ('Smartwatch', 'smartwatch', ['wrist', 'wearable', 'tech']),
            ('Television', 'television', ['screen', 'shows', 'display']),
            ('Monitor', 'monitor', ['screen', 'display', 'computer']),
            ('Keyboard', 'keyboard', ['typing', 'keys', 'input']),
            ('Mouse', 'mouse', ['clicking', 'cursor', 'input']),
            ('Printer', 'printer', ['paper', 'ink', 'output']),
            ('Scanner', 'scanner', ['documents', 'digital', 'input']),
            ('Speaker', 'speaker', ['audio', 'sound', 'output']),
            ('Headphones', 'headphones', ['audio', 'ears', 'listening']),
            ('Microphone', 'microphone', ['audio', 'recording', 'input']),
            ('Camera', 'camera', ['photos', 'video', 'recording']),
            ('Webcam', 'webcam', ['video', 'computer', 'streaming']),
            ('Router', 'router', ['network', 'internet', 'connection']),
            ('Modem', 'modem', ['internet', 'connection', 'signal']),
            ('Switch', 'switch', ['network', 'connection', 'ports']),
            ('Server', 'server', ['network', 'hosting', 'data']),
            ('Hard Drive', 'hard_drive', ['storage', 'data', 'disk']),
            ('Solid State Drive', 'solid_state_drive', ['storage', 'fast', 'flash']),
            ('Flash Drive', 'flash_drive', ['usb', 'portable', 'storage']),
            ('Memory Card', 'memory_card', ['storage', 'camera', 'small']),
            ('Processor', 'processor', ['cpu', 'brain', 'computer']),
            ('Motherboard', 'motherboard', ['circuit', 'main', 'board']),
            ('Graphics Card', 'graphics_card', ['gpu', 'video', 'rendering']),
            ('Power Supply', 'power_supply', ['electricity', 'computer', 'unit']),
            ('Battery', 'battery', ['power', 'portable', 'energy']),
            ('Charger', 'charger', ['power', 'plug', 'cable']),
            ('Cable', 'cable', ['wire', 'connection', 'cord']),
            ('Adapter', 'adapter', ['connector', 'plug', 'converter']),
            ('Software', 'software', ['programs', 'code', 'applications']),
            ('Operating System', 'operating_system', ['windows', 'mac', 'linux']),
            ('Application', 'application', ['app', 'program', 'software']),
            ('Browser', 'browser', ['web', 'internet', 'surfing']),
            ('Search Engine', 'search_engine', ['google', 'finding', 'web']),
            ('Website', 'website', ['pages', 'internet', 'domain']),
            ('Domain', 'domain', ['address', 'web', 'name']),
            ('URL', 'url', ['link', 'web', 'address']),
            ('IP Address', 'ip_address', ['network', 'number', 'location']),
            ('Protocol', 'protocol', ['rules', 'network', 'communication']),
            ('Network', 'network', ['connected', 'devices', 'internet']),
            ('Internet', 'internet', ['global', 'network', 'web']),
            ('Intranet', 'intranet', ['private', 'network', 'company']),
            ('Cloud', 'cloud', ['storage', 'internet', 'servers']),
            ('Database', 'database', ['storage', 'data', 'organized']),
            ('Algorithm', 'algorithm', ['rules', 'problem', 'solving']),
            ('Code', 'code', ['programming', 'text', 'instructions']),
            ('Programming', 'programming', ['coding', 'writing', 'software']),
            ('Developer', 'developer', ['coder', 'programmer', 'software']),
            ('Hacker', 'hacker', ['security', 'breach', 'code']),
            ('Virus', 'virus', ['malware', 'infection', 'computer']),
            ('Malware', 'malware', ['harmful', 'software', 'virus']),
            ('Spyware', 'spyware', ['snooping', 'software', 'tracking']),
            ('Ransomware', 'ransomware', ['extortion', 'software', 'encryption']),
            ('Firewall', 'firewall', ['security', 'network', 'protection']),
            ('Encryption', 'encryption', ['security', 'scrambling', 'data']),
            ('Password', 'password', ['security', 'login', 'secret']),
            ('Authentication', 'authentication', ['security', 'login', 'verifying']),
            ('Biometrics', 'biometrics', ['fingerprint', 'face', 'recognition']),
            ('Artificial Intelligence', 'artificial_intelligence', ['ai', 'machine', 'learning']),
            ('Machine Learning', 'machine_learning', ['ai', 'training', 'data']),
            ('Neural Network', 'neural_network', ['ai', 'brain', 'model']),
            ('Deep Learning', 'deep_learning', ['ai', 'neural', 'networks']),
            ('Robotics', 'robotics', ['machines', 'automation', 'bots']),
            ('Automation', 'automation', ['machines', 'tasks', 'robots']),
            ('Virtual Reality', 'virtual_reality', ['vr', 'headset', 'immersion']),
            ('Augmented Reality', 'augmented_reality', ['ar', 'overlay', 'world']),
            ('Mixed Reality', 'mixed_reality', ['mr', 'blending', 'worlds']),
            ('Blockchain', 'blockchain', ['crypto', 'ledger', 'decentralized']),
            ('Cryptocurrency', 'cryptocurrency', ['bitcoin', 'digital', 'money']),
            ('NFT', 'nft', ['crypto', 'token', 'art']),
            ('Smart Home', 'smart_home', ['automation', 'devices', 'connected']),
            ('Internet of Things', 'internet_of_things', ['iot', 'connected', 'devices']),
            ('5G', '5g', ['cellular', 'network', 'fast']),
            ('Wi-Fi', 'wi_fi', ['wireless', 'network', 'internet']),
            ('Bluetooth', 'bluetooth', ['wireless', 'connection', 'short']),
            ('NFC', 'nfc', ['wireless', 'payment', 'contactless']),
            ('GPS', 'gps', ['location', 'navigation', 'satellite']),
            ('Satellite', 'satellite', ['orbit', 'space', 'communication']),
            ('Drone', 'drone', ['flying', 'unmanned', 'aerial']),
            ('3D Printing', '3d_printing', ['creating', 'objects', 'layers']),
            ('Laser', 'laser', ['light', 'beam', 'focused']),
            ('Fiber Optics', 'fiber_optics', ['light', 'cables', 'fast']),
            ('Quantum Computing', 'quantum_computing', ['qubits', 'fast', 'processing']),
            ('Nanotechnology', 'nanotechnology', ['microscopic', 'tech', 'tiny']),
            ('Biotechnology', 'biotechnology', ['biology', 'tech', 'science']),
            ('Genetic Engineering', 'genetic_engineering', ['dna', 'modification', 'tech']),
            ('Cybersecurity', 'cybersecurity', ['protection', 'networks', 'hackers']),
            ('Data Science', 'data_science', ['analysis', 'information', 'statistics']),
            ('Big Data', 'big_data', ['massive', 'information', 'analysis']),
            ('Cloud Computing', 'cloud_computing', ['servers', 'internet', 'services']),
            ('SaaS', 'saas', ['software', 'service', 'subscription']),
            ('PaaS', 'paas', ['platform', 'service', 'cloud']),
            ('IaaS', 'iaas', ['infrastructure', 'service', 'cloud']),
            ('Open Source', 'open_source', ['free', 'code', 'community']),
            ('API', 'api', ['interface', 'software', 'connection']),
            ('SDK', 'sdk', ['development', 'kit', 'software']),
            ('IDE', 'ide', ['development', 'environment', 'coding']),
            ('Framework', 'framework', ['software', 'foundation', 'building']),
            ('Library', 'library', ['code', 'collection', 'reusable']),
            ('Repository', 'repository', ['storage', 'code', 'version']),
            ('Version Control', 'version_control', ['git', 'tracking', 'changes']),
            ('DevOps', 'devops', ['development', 'operations', 'collaboration']),
            ('Agile', 'agile', ['development', 'methodology', 'flexible']),
            ('Scrum', 'scrum', ['agile', 'framework', 'sprints']),
            ('Kanban', 'kanban', ['agile', 'board', 'visual']),
            ('UI', 'ui', ['user', 'interface', 'design']),
            ('UX', 'ux', ['user', 'experience', 'design']),
            ('Frontend', 'frontend', ['client', 'side', 'web']),
            ('Backend', 'backend', ['server', 'side', 'web']),
            ('Full Stack', 'full_stack', ['frontend', 'backend', 'developer']),
            ('Database Administrator', 'database_administrator', ['dba', 'managing', 'data']),
            ('System Administrator', 'system_administrator', ['sysadmin', 'managing', 'servers']),
            ('Network Administrator', 'network_administrator', ['managing', 'networks', 'admin']),
            ('Security Analyst', 'security_analyst', ['protecting', 'systems', 'cyber']),
            ('Data Analyst', 'data_analyst', ['analyzing', 'information', 'stats']),
            ('Microchip', 'microchip', ['silicon', 'circuit', 'tiny']),
            ('Mainframe', 'mainframe', ['large', 'computer', 'system'])
        ]
    }
}

for cat, info in data.items():
    words_list = info['words']
    if len(words_list) < 120:
        raise ValueError(f"{cat} has only {len(words_list)} words, need 120!")
    words_list = words_list[:120]

    json_data = []
    ts_content = "import type { WordEntry } from '../../../types/packs'\n\n"
    ts_content += f"export const {info['export_name']}: WordEntry[] = [\n"

    for i, (word, wid, hints) in enumerate(words_list):
        entry = {
            'id': wid,
            'word': word,
            'category': info['category'],
            'hints': hints
        }
        json_data.append(entry)
        
        hint_str = ', '.join([f'"{h}"' for h in hints])
        ts_content += f'  {{ "id": "{wid}", "word": "{word}", "category": "{info["category"]}", "hints": [{hint_str}] }}'
        if i < len(words_list) - 1:
            ts_content += ",\n"
        else:
            ts_content += "\n"
            
    ts_content += "]\n"

    json_str = json.dumps(json_data, indent=2)

    with open(f"{cat}_temp.ts", "w", encoding="utf-8") as f:
        f.write(ts_content)
    with open(f"{cat}_temp.json", "w", encoding="utf-8") as f:
        f.write(json_str)

    subprocess.run(["powershell", "-Command", f"Get-Content {cat}_temp.ts -Raw | Set-Content -Path '{info['ts_file']}' -Encoding UTF8"], check=True)
    subprocess.run(["powershell", "-Command", f"Get-Content {cat}_temp.json -Raw | Set-Content -Path '{info['json_file']}' -Encoding UTF8"], check=True)
    
    os.remove(f"{cat}_temp.ts")
    os.remove(f"{cat}_temp.json")

print('Done')
